config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  ActiveAdmin.routes(self)
  root to: "plants#index"
  resources :plants, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :orders, only: [:index, :show]
  resources :plant_types, only: [:show]
  resources :cart, only: [:index, :create, :destroy] do
    post 'invoice', on: :collection
  end

  scope "/checkout" do
    get "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    product_id = params[:id]
    quantity = params[:quantity].to_i
    plant = Plant.find_by(id: product_id)
    if session[:shopping_cart].key?(product_id)
      if params[:source].present?
        session[:shopping_cart][product_id] = quantity
        redirect_to cart_index_path
      else
        session[:shopping_cart][product_id] += quantity
        flash[:notice] = "#{quantity} #{plant.name} added to cart."
        redirect_to plant_path(product_id)
      end
    else
      session[:shopping_cart][product_id] = quantity
      redirect_to plant_path(product_id)
    end

    plant = Plant.find(product_id)
    flash[:notice] = "#{quantity} #{plant.name} added to cart."
  end

  def destroy
    id = params[:id]
    session[:shopping_cart].delete(id)
    plant = Plant.find(id)

    flash[:notice] = "#{plant.name} removed from cart."
    redirect_to cart_index_path
  end

  def index
    cart_items = session[:shopping_cart]
    @cart_products = Plant.where(id: cart_items.keys)
    @cart_items_with_quantity = {}
    @cart_products.each do |product|
      quantity = cart_items[product.id.to_s]
      @cart_items_with_quantity[product] = quantity
    end
    @subtotal = 0
    @cart_items_with_quantity.each do |plant, quantity|
     @subtotal += plant.price * quantity
    end
  end

  def invoice
    customer = User.find_by(id: current_user.id)

    @cart_items_with_quantity = session[:shopping_cart]

    order = customer.orders.new

    @total_price = 0
    @gst_total = 0
    @pst_total = 0
    @hst_total = 0
    @cart_items_with_quantity.each do |product_id, quantity|
      product = Plant.find_by(id: product_id.to_i)
      product_multiply_quantity = product.price * quantity
      product_gst = (customer.tax_rate.gst / 100) * product_multiply_quantity
      product_pst = (customer.tax_rate.pst / 100) * product_multiply_quantity
      product_hst = (customer.tax_rate.hst / 100) * product_multiply_quantity
      @gst_total = @gst_total + product_gst
      @pst_total = @pst_total + product_pst
      @hst_total = @hst_total + product_hst
      @total_price = @total_price + product_multiply_quantity

      product.update(stock: product.stock - quantity)

      order_plant = order.order_plants.build(
        quantity: quantity,
        ordered_price: product.price,
        plant_id: product.id
      )
    end
    order.total = @total_price
    order.gst_tax = @gst_total
    order.pst_tax = @pst_total
    order.hst_tax = @hst_total
    order.order_status_id = 1
    order.save

    session[:shopping_cart] = {}
    redirect_to checkout_create_path + "?order_id=#{order.id}"
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<section class="section">
  <%if @cart_items_with_quantity.empty?%>
    <h1 class="title has-text-centered has-text-grey">
      There's no Item in the cart.
    </h1>
  <%else%>
  <h1 class="title has-text-centered">
    Cart
  </h1>
  <h2 class="title has-text-centered">
    Subtotal: CA$<%= @subtotal%>
  </h2>
  <div class="has-text-centered mb-3">
    <% if current_user %>
      <%= button_to "Purchase", invoice_cart_index_path, data: { turbo: false }, class: "button is-primary" %>
    <% else %>
      <%= link_to "Sign Up to Purchase", new_user_registration_path, class: "button is-primary" %>
    <% end %>
    <%end%>
  </div>
  <% @cart_items_with_quantity.each do |plant, quantity| %>
    <div class="box">
      <ul class="columns is-multiline">
        <li class="column is-one-fifth">
          <%= image_tag(plant.image, alt: "#{plant.name} Image") %>
        </li>
        <li>
          <h1 class="title is-4">
            <%= link_to plant.name, plant %>
            CA$<%= plant.price * quantity%>
          </h1>
          <%=form_with(url: cart_index_path, method: :post, local: true )do%>
            <%= hidden_field_tag(:id, plant.id)%>
            <%= hidden_field_tag(:source, 'index')%>
            <%= label_tag :quantity, "Quantity", class: "label" %>
            <p>In cart: <%= quantity%></p>
            <div class="field-body has-addon">
              <div class="control">
                <div class="field is-narrow">
                    <%= number_field_tag(:quantity, quantity, min: 1 , class: "input is-primary mb-1" )%>
                </div>
              </div>
              <div class="control">
                <%= button_tag 'Update Quantity',class: "button is-primary mb-1" %>
              </div>
            </div>
          <%end%>
          <%= button_to cart_path(plant), method: :delete, class: "button is-danger is-outlined" do %>
            Remove from cart.
          <%end%>
        </li>
      </ul>
    </div>
  <% end %>
<section>