config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  ActiveAdmin.routes(self)
  root to: "plants#index"
  resources :plants, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :orders, only: [:index, :show]
  resources :plant_types, only: [:show]
  resources :cart, only: [:index, :create, :destroy] do
    post 'invoice', on: :collection
  end

  scope "/checkout" do
    get "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :order_status
  has_many :order_plants

  validates :gst_tax, :hst_tax, :pst_tax, :total, :user_id, presence: true
  validates :gst_tax, :hst_tax, :pst_tax, :total, numericality: { greater_than_or_equal_to: 0}

  def self.ransackable_associations(auth_object = nil)
    ["order_plants", "order_status", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "gst_tax", "hst_tax", "id", "id_value", "order_status_id", "payment_id", "pst_tax", "total", "updated_at", "user_id"]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
    unless current_user.orders.include?(@order)
      redirect_to orders_path
    end
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/index.html.erb
<section class="section">
<div class="box">
  <% if @orders.empty? %>
    <div class="container">
      <h1 class="title has-text-centered has-text-grey">
        There are no orders that have been made yet.
      </h1>
    </div>
  <% else %>
    <h1 class="title has-text-centered">Order History</h1>
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Order#</th>
          <th>Ordered Date</th>
          <th>Total Cost</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <% total_cost = order.total + order.gst_tax + order.pst_tax + order.hst_tax %>
          <tr>
            <td><%= link_to "Order ##{order.id}", order %></td>
            <td><%= order.created_at.strftime("%B %d, %Y") %></td>
            <td><%= number_to_currency(total_cost) %></td>
            <td>
              <% if order.order_status_id == 1 %>
                <%= link_to "Pay now", checkout_create_path + "?order_id=#{order.id}"%>
              <% else %>
                <%= order.order_status.status %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</section>
</div>

app/views/orders/show.html.erb
<section class="section">
  <div class="box">
    <h1 class="title has-text-centered mb-5">
      Order #<%= @order.id %>
    </h1>
    <h2 class="subtitle is-3 has-text-centered mb-4">
      Status: <%= @order.order_status.status %>
    </h2>
    <div class="table-container">
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Product</th>
            <th class="has-text-centered">Quantity</th>
            <th class="has-text-centered">Unit Price</th>
            <th class="has-text-centered">Total Product Price</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_plants.each do |ordered_plant| %>
            <% plant = Plant.find_by(id: ordered_plant.plant_id) %>
            <tr>
              <td><%= link_to plant.name, plant %></td>
              <td class="has-text-centered"><%= ordered_plant.quantity %></td>
              <td class="has-text-centered"><%= number_to_currency(ordered_plant.ordered_price) %></td>
              <td class="has-text-centered"><%= number_to_currency(ordered_plant.quantity * ordered_plant.ordered_price) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <p><strong>Total: </strong><%= number_to_currency(@order.total) %></p>
    <p><strong>GST: </strong><%= number_to_currency(@order.gst_tax) %></p>
    <p><strong>PST: </strong><%= number_to_currency(@order.pst_tax) %></p>
    <p><strong>HST: </strong><%= number_to_currency(@order.hst_tax) %></p>
    <% total_cost = @order.total + @order.gst_tax + @order.pst_tax + @order.hst_tax %>
    <p><strong>Total + Tax: </strong><%= number_to_currency(total_cost) %></p>
    <% if @order.order_status_id == 1 %>
      <div class="column is-full has-text-centered">
        <%= link_to "Purchase", checkout_create_path + "?order_id=#{@order.id}", class: "button is-primary purchase-button" %>
      </div>
    <% end %>
  </div>
</section>