config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  ActiveAdmin.routes(self)
  root to: "plants#index"
  resources :plants, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :orders, only: [:index, :show]
  resources :plant_types, only: [:show]
  resources :cart, only: [:index, :create, :destroy] do
    post 'invoice', on: :collection
  end

  scope "/checkout" do
    get "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/common/_navbar.html.erb
<header class="mb-1">
  <div class="box">
  <nav class="navbar mx-6" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href ="<%= root_path %>">
        <%= image_tag("leaf.png", alt: "An icon of a four leaf Plant.") %>
        Evergreen Enclave
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href ="<%= plants_path %>">
          Plants
        </a>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Plant Type
          </a>
          <div class="navbar-dropdown">
            <% PlantType.all.each do |plant_type| %>
              <ul>
                <li>
                  <%= link_to plant_type.name, plant_type %>
                </li>
              </ul>
            <% end %>
            <%= link_to "Recently added", plants_path(status: "new") %>
            <%= link_to "Recently updated", plants_path(status: "update") %>
          </div>
        </div>
        <div class="navbar-item" >
          <a class="button is-primary is-outlined" href ="<%= cart_index_path %>">
            <span class="icon-text">
              <span class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </span>
              <span><%= session[:shopping_cart].count %></span>
            </span>
          </a>
        </div>
      </div>
      <div class="navbar-end">
        <%= form_with(url: search_plants_path, method: :get, local: true) do %>
          <div class="navbar-item">
            <%= text_field_tag(:keywords, nil, class: "input is-primary", placeholder: "Search for a plant")%>
            <div class="control">
              <div class="select">
                <%= select_tag(:type, options_for_select(PlantType.all.map { |plant_type| [plant_type.name] }), { include_blank: 'All' }) %>
              </div>
            </div>
            <%= submit_tag("Search", class: "button is-primary")%>
          </div>
        <% end %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <% if user_signed_in? %>
              <span class="icon-text">
                <span class="icon">
                  <i class="fa-solid fa-user"></i>
                </span>
                <span><%= current_user.firstname %></span>
              </span>
            <% else %>
              Log-in/Sign-up
            <% end %>
          </a>
          <div class="navbar-dropdown">
            <% if user_signed_in? %>
              <a class="navbar-item" href ="<%= orders_path %>">
                Orders
              </a>
              <%= link_to "Profile", edit_user_registration_path , class: "navbar-item" %>
              <%= form_tag destroy_user_session_path, method: :delete do %>
                <%= submit_tag "Log Out", class: "button is-text"  %>
              <% end %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, class: "navbar-item" %>
              <%= link_to "Log In", new_user_session_path, class: "navbar-item" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
  </div>
</header>